---
- name: Ensure slapd of global config options were configured
  become: yes
  ldap_attrs:
    dn: "cn=config"
    attributes:
      olcIdleTimeout: '{{ slapd_idletimeout | default(omit) }}'
      olcLogLevel: '{{ slapd_loglevel | default(omit) }}'
      olcSizeLimit: '{{ slapd_sizelimit | default(omit) }}'
      olcReferral: '{{ slapd_referral | default(omit) }}'
    state: exact
