---
- include_tasks: "variables.yml"
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: "variables-hashed-passwd.yml"
- include_tasks: "configure.yml"
- include_tasks: "configure-global-options.yml"
- include_tasks: "configure-basedn.yml"
- include_tasks: "configure-admin.yml"
- include_tasks: "module-memberof.yml"
  when: ldap_install_module_memberof
- include_tasks: "module-refint.yml"
  when: ldap_install_module_refint or ldap_install_module_memberof
- include_tasks: "schema-ssh-lpk.yml"
  when: ldap_enable_schema_ssh_lpk
- include_tasks: "schema-sudo.yml"
  when: ldap_enable_schema_sudo
