---
- include_tasks: "variables.yml"
- include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "setup-{{ ansible_os_family }}.yml"
- include_tasks: "variables-hashed-passwd.yml"
- include_tasks: "variables-database-type.yml"
- include_tasks: "configure.yml"
- include_tasks: "configure-global-options.yml"
- include_tasks: "configure-basedn.yml"
- include_tasks: "configure-admin.yml"
- include_tasks: "module-memberof.yml"
  when: slapd_install_module_memberof
- include_tasks: "module-refint.yml"
  when: slapd_install_module_refint or slapd_install_module_memberof
- include_tasks: "schema-cosine.yml"
  when: slapd_install_schema_cosine or slapd_install_schema_nis
- include_tasks: "schema-nis.yml"
  when: slapd_install_schema_nis
- include_tasks: "schema-misc.yml"
  when: slapd_install_schema_misc
- include_tasks: "schema-ssh-lpk.yml"
  when: slapd_install_schema_ssh_lpk
- include_tasks: "schema-sudo.yml"
  when: slapd_install_schema_sudo
- include_tasks: "schema-samba3.yml"
  when: slapd_install_schema_samba3
