---
- name: "Check the memberof.la module was already loaded"
  become: true
  community.general.ldap_search:
    dn: "cn=config"
    scope: "onelevel"
    filter: "(&(objectClass=olcModuleList)(olcModuleLoad=memberof.la))"
  check_mode: false
  register: module_memberof
  when: slapd_module_memberof_dn is not defined

- name:  Define slapd_module_memberof_dn
  set_fact:
    slapd_module_memberof_dn: >-
      {%- if module_memberof.results[0] is defined -%}
      {{ module_memberof.results[0].dn }}
      {%- else -%}
      cn=module,cn=config
      {%- endif -%}
  when: slapd_module_memberof_dn is not defined

- name: "Ensure a module memberof.la was loaded"
  become: true
  ldap_entry:
    dn: "{{ slapd_module_memberof_dn }}"
    objectClass:
      - olcModuleList
      - top
    attributes:
      cn: module
      olcModulePath: '{{ slapd_module_path }}'
      olcModuleLoad: memberof.la

- name: "Check the memberof overlay was already exists"
  become: true
  community.general.ldap_search:
    dn: '{{ slapd_olcDatabase_type_dn }}'
    schema: true
    scope: "onelevel"
    filter: "(&(olcOverlay=memberof)(objectClass=olcMemberOf))"
  check_mode: false
  register: overlay_memberof
  when: slapd_overlay_memberof_dn is not defined

- name:  Define slapd_overlay_memberof_dn
  set_fact:
    slapd_overlay_memberof_dn: >-
      {%- if overlay_memberof.results[0] is defined -%}
      {{ overlay_memberof.results[0].dn }}
      {%- else -%}
      olcOverlay=memberof,{{ slapd_olcDatabase_type_dn }}
      {%- endif -%}
  when: slapd_overlay_memberof_dn is not defined

- name: "Ensure the memberof overlay was registered"
  become: true
  ldap_entry:
    dn: "{{ slapd_overlay_memberof_dn }}"
    objectClass:
      - olcOverlayConfig
      - olcMemberOf
    attributes:
      olcOverlay: "memberof"
      olcMemberOfRefint: "TRUE"
