---
- name: "Check the refint.la module was already loaded"
  become: true
  community.general.ldap_search:
    dn: "cn=config"
    scope: "onelevel"
    filter: "(&(objectClass=olcModuleList)(olcModuleLoad=refint.la))"
  check_mode: false
  register: module_refint

- name: Define slapd_module_refint_dn
  set_fact:
    slapd_module_refint_dn: >-
      {%- if module_refint.results[0] is defined -%}
      {{ module_refint.results[0].dn }}
      {%- else -%}
      cn=module,cn=config
      {%- endif -%}
  when: slapd_module_refint_dn is not defined

- name: "Ensure a module refint.la was loaded"
  become: true
  ldap_entry:
    dn: "{{ slapd_module_refint_dn }}"
    objectClass:
      - olcModuleList
      - top
    attributes:
      cn: module
      olcModulePath: '{{ slapd_module_path }}'
      olcModuleLoad: refint.la
    state: present

- name: "Check the refint overlay was already exists"
  become: true
  community.general.ldap_search:
    dn: '{{ slapd_olcDatabase_type_dn }}'
    schema: true
    scope: "onelevel"
    filter: "(&(olcOverlay=refint)(objectClass=olcRefintConfig))"
  check_mode: false
  register: overlay_refint

- name: Define slapd_overlay_refint_dn
  set_fact:
    slapd_overlay_refint_dn: >-
      {%- if overlay_refint.results[0] is defined -%}
      {{ overlay_refint.results[0].dn }}
      {%- else -%}
      olcOverlay=refint,{{ slapd_olcDatabase_type_dn }}
      {%- endif -%}
  when: slapd_overlay_refint_dn is not defined

- name: "Ensure the refint overlay was registered"
  become: true
  ldap_entry:
    dn: "{{ slapd_overlay_refint_dn }}"
    objectClass:
      - olcOverlayConfig
      - olcRefintConfig
      - top
    attributes:
      olcOverlay: "refint"
      olcRefintAttribute: memberof member manager owner
