---
- name: "Check the ssh-lpk schema was already exists"
  become: true
  community.general.ldap_search:
    dn: "cn=schema,cn=config"
    schema: true
    scope: "onelevel"
    filter: "(&(cn={*}ssh-lpk)(objectClass=olcSchemaConfig))"
  check_mode: false
  register: schema_lpk
  when: slapd_schema_lpk_dn is not defined

- name: Define slapd_schema_lpk_dn
  set_fact:
    slapd_schema_lpk_dn: >-
      {%- if schema_lpk.results[0] is defined -%}
      {{ schema_lpk.results[0].dn }}
      {%- else -%}
      cn=ssh-lpk,cn=schema,cn=config
      {%- endif -%}
  when: slapd_schema_lpk_dn is not defined

- name: "Ensure the ssh-lpk schema was registered"
  become: true
  ldap_entry:
    dn: "{{ slapd_schema_lpk_dn }}"
    objectClass: "olcSchemaConfig"
    attributes:
      cn: "ssh-lpk"
      olcAttributeTypes:
        - "( 1.3.6.1.4.1.24552.500.1.1.1.13
             NAME 'sshPublicKey'
             DESC 'MANDATORY: OpenSSH Public key' EQUALITY octetStringMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 )"
      olcObjectClasses:
        - "( 1.3.6.1.4.1.24552.500.1.1.2.0
             NAME 'ldapPublicKey'
             DESC 'MANDATORY: OpenSSH LPK objectclass'
             SUP top AUXILIARY MUST ( sshPublicKey $ uid ) )"
