---
- name: "Check the cosine schema was already exists"
  become: true
  community.general.ldap_search:
    dn: "cn=schema,cn=config"
    schema: true
    scope: "onelevel"
    filter: "(&(cn={*}cosine)(objectClass=olcSchemaConfig))"
  check_mode: false
  register: schema_cosine

- name: Define slapd_schema_cosine_dn
  set_fact:
    slapd_schema_cosine_dn: >-
      {%- if schema_cosine.results[0] is defined -%}
      {{ schema_cosine.results[0].dn }}
      {%- else -%}
      cn=cosine,cn=schema,cn=config
      {%- endif -%}
  when: slapd_schema_cosine_dn is not defined

- name: "Ensure the cosine schema was registered"
  become: true
  ldap_entry:
    dn: "{{ slapd_schema_cosine_dn }}"
    objectClass: "olcSchemaConfig"
    attributes:
      cn: "cosine"
      olcAttributeTypes:
        - "( 0.9.2342.19200300.100.1.2 NAME 'textEncodedORAddress'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.4 NAME 'info'
             DESC 'RFC1274: general information'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{2048} )"
        - "( 0.9.2342.19200300.100.1.5
             NAME ( 'drink' 'favouriteDrink' )
             DESC 'RFC1274: favorite drink'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.6 NAME 'roomNumber'
             DESC 'RFC1274: room number'
             EQUALITY caseIgnoreMatch
            SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.7 NAME 'photo'
             DESC 'RFC1274: photo (G3 fax)'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.23{25000} )"
        - "( 0.9.2342.19200300.100.1.8 NAME 'userClass'
             DESC 'RFC1274: category of user'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.9 NAME 'host'
             DESC 'RFC1274: host computer'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.10 NAME 'manager'
             DESC 'RFC1274: DN of manager'
             EQUALITY distinguishedNameMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 )"
        - "( 0.9.2342.19200300.100.1.11 NAME 'documentIdentifier'
             DESC 'RFC1274: unique identifier of document'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.12 NAME 'documentTitle'
             DESC 'RFC1274: title of document'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.13 NAME 'documentVersion'
             DESC 'RFC1274: version of document'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.14 NAME 'documentAuthor'
             DESC 'RFC1274: DN of author of document'
             EQUALITY distinguishedNameMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 )"
        - "( 0.9.2342.19200300.100.1.15 NAME 'documentLocation'
             DESC 'RFC1274: location of document original'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.20
             NAME ( 'homePhone' 'homeTelephoneNumber' )
             DESC 'RFC1274: home telephone number'
             EQUALITY telephoneNumberMatch
             SUBSTR telephoneNumberSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.50 )"
        - "( 0.9.2342.19200300.100.1.21 NAME 'secretary'
             DESC 'RFC1274: DN of secretary'
             EQUALITY distinguishedNameMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 )"
        - "( 0.9.2342.19200300.100.1.22 NAME 'otherMailbox'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.39 )"
        ## Deprecated in favor of modifyTimeStamp
        # "( 0.9.2342.19200300.100.1.23 NAME 'lastModifiedTime'
        #    DESC 'RFC1274: time of last modify, replaced by modifyTimestamp'
        #    OBSOLETE
        #    SYNTAX 1.3.6.1.4.1.1466.115.121.1.53
        #    USAGE directoryOperation )"

        ## Deprecated in favor of modifiersName
        # "( 0.9.2342.19200300.100.1.24 NAME 'lastModifiedBy'
        #    DESC 'RFC1274: last modifier, replaced by modifiersName'
        #    OBSOLETE
        #    EQUALITY distinguishedNameMatch
        #    SYNTAX 1.3.6.1.4.1.1466.115.121.1.12
        #    USAGE directoryOperation )"

        ## incorrect syntax?
        - "( 0.9.2342.19200300.100.1.26 NAME 'aRecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        ## missing from RFC1274
        ## incorrect syntax?
        - "( 0.9.2342.19200300.100.1.27 NAME 'mDRecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        ## incorrect syntax!!
        - "( 0.9.2342.19200300.100.1.28 NAME 'mXRecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        ## incorrect syntax!!
        - "( 0.9.2342.19200300.100.1.29 NAME 'nSRecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        ## incorrect syntax!!
        - "( 0.9.2342.19200300.100.1.30 NAME 'sOARecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        ## incorrect syntax!!
        - "( 0.9.2342.19200300.100.1.31 NAME 'cNAMERecord'
             EQUALITY caseIgnoreIA5Match
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        # "( 0.9.2342.19200300.100.1.37 NAME 'associatedDomain'
        #    EQUALITY caseIgnoreIA5Match
        #    SUBSTR caseIgnoreIA5SubstringsMatch
        #    SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )"

        - "( 0.9.2342.19200300.100.1.38 NAME 'associatedName'
             DESC 'RFC1274: DN of entry associated with domain'
             EQUALITY distinguishedNameMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 )"
        - "( 0.9.2342.19200300.100.1.39 NAME 'homePostalAddress'
             DESC 'RFC1274: home postal address'
             EQUALITY caseIgnoreListMatch
             SUBSTR caseIgnoreListSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.41 )"
        - "( 0.9.2342.19200300.100.1.40 NAME 'personalTitle'
             DESC 'RFC1274: personal title'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.41
             NAME ( 'mobile' 'mobileTelephoneNumber' )
             DESC 'RFC1274: mobile telephone number'
             EQUALITY telephoneNumberMatch
             SUBSTR telephoneNumberSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.50 )"
        - "( 0.9.2342.19200300.100.1.42
             NAME ( 'pager' 'pagerTelephoneNumber' )
             DESC 'RFC1274: pager telephone number'
             EQUALITY telephoneNumberMatch
             SUBSTR telephoneNumberSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.50 )"
        - "( 0.9.2342.19200300.100.1.43
             NAME ( 'co' 'friendlyCountryName' )
             DESC 'RFC1274: friendly country name'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )"
        - "( 0.9.2342.19200300.100.1.44 NAME 'uniqueIdentifier'
             DESC 'RFC1274: unique identifer'
             EQUALITY caseIgnoreMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.45 NAME 'organizationalStatus'
             DESC 'RFC1274: organizational status'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.46 NAME 'janetMailbox'
             DESC 'RFC1274: Janet mailbox'
             EQUALITY caseIgnoreIA5Match
             SUBSTR caseIgnoreIA5SubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.26{256} )"
        - "( 0.9.2342.19200300.100.1.47
             NAME 'mailPreferenceOption'
             DESC 'RFC1274: mail preference option'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.27 )"
        - "( 0.9.2342.19200300.100.1.48 NAME 'buildingName'
             DESC 'RFC1274: name of building'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} )"
        - "( 0.9.2342.19200300.100.1.49 NAME 'dSAQuality'
             DESC 'RFC1274: DSA Quality'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.19 SINGLE-VALUE )"
        - "( 0.9.2342.19200300.100.1.50 NAME 'singleLevelQuality'
             DESC 'RFC1274: Single Level Quality'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.13 SINGLE-VALUE )"
        - "( 0.9.2342.19200300.100.1.51 NAME 'subtreeMinimumQuality'
             DESC 'RFC1274: Subtree Mininum Quality'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.13 SINGLE-VALUE )"
        - "( 0.9.2342.19200300.100.1.52 NAME 'subtreeMaximumQuality'
             DESC 'RFC1274: Subtree Maximun Quality'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.13 SINGLE-VALUE )"
        - "( 0.9.2342.19200300.100.1.53 NAME 'personalSignature'
             DESC 'RFC1274: Personal Signature (G3 fax)'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.23 )"
        - "( 0.9.2342.19200300.100.1.54 NAME 'dITRedirect'
             DESC 'RFC1274: DIT Redirect'
             EQUALITY distinguishedNameMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 )"
        - "( 0.9.2342.19200300.100.1.55 NAME 'audio'
             DESC 'RFC1274: audio (u-law)'
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.4{25000} )"
        - "( 0.9.2342.19200300.100.1.56 NAME 'documentPublisher'
             DESC 'RFC1274: publisher of document'
             EQUALITY caseIgnoreMatch
             SUBSTR caseIgnoreSubstringsMatch
             SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )"
      olcObjectClasses:
        # "( 0.9.2342.19200300.100.4.3 NAME 'pilotObject'
        #    DESC 'RFC1274: pilot object'
        #    SUP top AUXILIARY
        #    MAY ( info $ photo $ manager $ uniqueIdentifier $
        #      lastModifiedTime $ lastModifiedBy $ dITRedirect $ audio )
        #    )"

        - "( 0.9.2342.19200300.100.4.4
             NAME ( 'pilotPerson' 'newPilotPerson' )
             SUP person STRUCTURAL
             MAY ( userid $ textEncodedORAddress $ rfc822Mailbox $
               favouriteDrink $ roomNumber $ userClass $
               homeTelephoneNumber $ homePostalAddress $ secretary $
               personalTitle $ preferredDeliveryMethod $ businessCategory $
               janetMailbox $ otherMailbox $ mobileTelephoneNumber $
               pagerTelephoneNumber $ organizationalStatus $
               mailPreferenceOption $ personalSignature )
             )"
        - "( 0.9.2342.19200300.100.4.5 NAME 'account'
             SUP top STRUCTURAL
             MUST userid
             MAY ( description $ seeAlso $ localityName $
               organizationName $ organizationalUnitName $ host )
             )"
        - "( 0.9.2342.19200300.100.4.6 NAME 'document'
             SUP top STRUCTURAL
             MUST documentIdentifier
             MAY ( commonName $ description $ seeAlso $ localityName $
               organizationName $ organizationalUnitName $
               documentTitle $ documentVersion $ documentAuthor $
               documentLocation $ documentPublisher )
             )"
        - "( 0.9.2342.19200300.100.4.7 NAME 'room'
             SUP top STRUCTURAL
             MUST commonName
             MAY ( roomNumber $ description $ seeAlso $ telephoneNumber )
             )"
        - "( 0.9.2342.19200300.100.4.9 NAME 'documentSeries'
             SUP top STRUCTURAL
             MUST commonName
             MAY ( description $ seeAlso $ telephonenumber $
               localityName $ organizationName $ organizationalUnitName )
             )"
        - "( 0.9.2342.19200300.100.4.13 NAME 'domain'
             SUP top STRUCTURAL
             MUST domainComponent
             MAY ( associatedName $ organizationName $ description $
               businessCategory $ seeAlso $ searchGuide $ userPassword $
               localityName $ stateOrProvinceName $ streetAddress $
               physicalDeliveryOfficeName $ postalAddress $ postalCode $
               postOfficeBox $ streetAddress $
               facsimileTelephoneNumber $ internationalISDNNumber $
               telephoneNumber $ teletexTerminalIdentifier $ telexNumber $
               preferredDeliveryMethod $ destinationIndicator $
               registeredAddress $ x121Address )
             )"
        - "( 0.9.2342.19200300.100.4.14 NAME 'RFC822localPart'
             SUP domain STRUCTURAL
             MAY ( commonName $ surname $ description $ seeAlso $ telephoneNumber $
               physicalDeliveryOfficeName $ postalAddress $ postalCode $
               postOfficeBox $ streetAddress $
               facsimileTelephoneNumber $ internationalISDNNumber $
               telephoneNumber $ teletexTerminalIdentifier $
               telexNumber $ preferredDeliveryMethod $ destinationIndicator $
               registeredAddress $ x121Address )
             )"
        - "( 0.9.2342.19200300.100.4.15 NAME 'dNSDomain'
             SUP domain STRUCTURAL
             MAY ( ARecord $ MDRecord $ MXRecord $ NSRecord $
               SOARecord $ CNAMERecord )
             )"
        - "( 0.9.2342.19200300.100.4.17 NAME 'domainRelatedObject'
             DESC 'RFC1274: an object related to an domain'
             SUP top AUXILIARY
             MUST associatedDomain )"
        - "( 0.9.2342.19200300.100.4.18 NAME 'friendlyCountry'
             SUP country STRUCTURAL
             MUST friendlyCountryName )"
        - "( 0.9.2342.19200300.100.4.20 NAME 'pilotOrganization'
             SUP ( organization $ organizationalUnit ) STRUCTURAL
             MAY buildingName )"
        - "( 0.9.2342.19200300.100.4.21 NAME 'pilotDSA'
             SUP dsa STRUCTURAL
             MAY dSAQuality )"
        - "( 0.9.2342.19200300.100.4.22 NAME 'qualityLabelledData'
             SUP top AUXILIARY
             MUST dsaQuality
             MAY ( subtreeMinimumQuality $ subtreeMaximumQuality )
             )"
