---
- name: Enable DNF module
  become: true
  command:
    argv:
      - dnf
      - -y
      - module
      - enable
      - 389-ds

- name: Install LDAP packages.
  become: true
  dnf:
    name: "{{ ldap_server_packages }}"

- name: Install python packages for LDAP.
  become: true
  dnf:
    name: "{{ ldap_python_modules }}"
  when: not slapd_install_python_module_via_pip

- name: Install python packages for LDAP using pip.
  become: true
  pip:
    name: "{{ ldap_python_modules_pip }}"
  when: slapd_install_python_module_via_pip
