---
- block:
    - name: Generate hashed password of LDAP root
      command:
        argv:
          - slappasswd
          - -h
          - '{{ ldap_passwd_scheme }}'
          - -s
          - '{{ ldap_root_passwd }}'
      changed_when: false
      register: cmd_ldap_root_hashed_passwd
    - name: Define ldap_root_hashed_passwd
      set_fact:
        ldap_root_hashed_passwd: '{{ cmd_ldap_root_hashed_passwd.stdout }}'
  when: ldap_root_hashed_passwd is not defined

- block:
    - name: Generate hashed password of LDAP administrator
      command:
        argv:
          - slappasswd
          - -h
          - '{{ ldap_passwd_scheme }}'
          - -s
          - '{{ ldap_admin_passwd }}'
      changed_when: false
      register: cmd_ldap_admin_hashed_passwd
    - name: Define ldap_admin_hashed_passwd
      set_fact:
        ldap_admin_hashed_passwd: '{{ cmd_ldap_admin_hashed_passwd.stdout }}'
  when: ldap_admin_hashed_passwd is not defined
