---
- name: Include OS-specfic variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Define ldap_server_packages
  set_fact:
    ldap_server_packages: "{{ __ldap_server_packages | list }}"
  when: ldap_server_packages is not defined

- name: Define ldap_python_modules
  set_fact:
    ldap_python_modules: "{{ __ldap_python_modules | list }}"
  when: ldap_python_modules is not defined

- name: Define ldap_python_modules_pip
  set_fact:
    ldap_python_modules_pip: "{{ __ldap_python_modules_pip | list }}"
  when: ldap_python_modules_pip is not defined

- name: Define slapd_install_python_module_via_pip
  set_fact:
    slapd_install_python_module_via_pip: "{{ __slapd_install_python_module_via_pip }}"
  when: slapd_install_python_module_via_pip is not defined

- name: Define ldap_owner
  set_fact:
    ldap_owner: "{{ __ldap_owner }}"
  when: ldap_owner is not defined

- name: Define ldap_group
  set_fact:
    ldap_group: "{{ __ldap_group }}"
  when: ldap_group is not defined

- name: Define ldap_conf_file
  set_fact:
    ldap_conf_file: "{{ __ldap_conf_file }}"
  when: ldap_conf_file is not defined

- name: Define slapd_daemon
  set_fact:
    slapd_daemon: "{{ __slapd_daemon }}"
  when: slapd_daemon is not defined

# Set ldap_admin_basedn to ldap_basedn then it does not defined.
- name: Define ldap_admin_basedn
  set_fact:
    ldap_admin_basedn: "{{ ldap_basedn }}"
  when: ldap_admin_basedn is not defined

- name: Define slapd_conf_file
  set_fact:
    slapd_conf_file: "{{ __slapd_conf_file }}"
  when: slapd_conf_file is not defined

- name: Define slapd_module_path
  set_fact:
    slapd_module_path: "{{ __slapd_module_path }}"
  when: slapd_module_path is not defined

- name: Define slapd_db_type
  set_fact:
    slapd_db_type: "{{ __slapd_db_type }}"
  when: slapd_db_type is not defined

- name: Define ldap_admin_dn
  set_fact:
    ldap_admin_dn: "{{ ldap_admin }},{{ ldap_admin_basedn }}"
  when: ldap_admin_dn is not defined
